name: PollPlugin
version: ${project.version}
main: de.marvinleiers.pollplugin.PollPlugin
api-version: 1.15
authors: [ Marvin2k0 ]
website: www.marvinleiers.de

commands:
  umfrage:
    permission: poll.admin
  abstimmen:

